// Generated by CoffeeScript 1.6.1
(function() {
  var $;

  $ = jQuery;

  $(function() {
    return $('.drag_exercise').each(function() {
      return $(this).dragExcercise();
    });
  });

}).call(this);
