// Generated by CoffeeScript 1.6.1
(function() {
  var $, add_dictionary_note, add_to_dictionary, dictionary, dictionary_form, init_state, load_dictionary, save_dictionary, show_popup, state;

  $ = jQuery;

  show_popup = function(text, x, y, duration) {
    var popup;
    if (duration == null) {
      duration = 2000;
    }
    popup = $('<div class="popup"></div>').html(text);
    popup.css({
      'left': x - popup.width() / 2 + pageXOffset,
      'top': y + 10 + pageYOffset
    }).click(function() {
      return $(this).remove();
    }).delay(duration / 5 * 4).fadeOut(duration / 5).queue(function() {
      return $(this).remove();
    });
    return $('body').append(popup);
  };

  dictionary = {};

  save_dictionary = function() {
    return localStorage.setItem('dictionary', JSON.stringify(dictionary));
  };

  load_dictionary = function() {
    return dictionary = JSON.parse(localStorage.getItem('dictionary')) || {};
  };

  add_to_dictionary = function(key, value, $elements) {
    console.log('adding to dictionary:', key, value);
    dictionary[key] = value;
    if ($elements != null) {
      $elements.each(function() {
        return $(this).html(function(i, text) {
          return text.replace(RegExp("\\b" + key + "\\b(?!>)", 'g'), '<span class="word">$&</span>');
        });
      });
      return $('.word').click(function(evt) {
        return show_popup(dictionary[$(this).html()], evt.clientX, evt.clientY);
      });
    }
  };

  $.fn.bindDictionaryLookup = function() {
    var meaning, word, _results;
    load_dictionary();
    _results = [];
    for (word in dictionary) {
      meaning = dictionary[word];
      _results.push(add_to_dictionary(word, meaning, $(this)));
    }
    return _results;
  };

  dictionary_form = _.template("<div class=\"modal_window\">\n    <h3><%= key %></h3>\n    <textarea cols=\"80\" rows=\"5\"><%= value %></textarea>\n</div>");

  init_state = function() {
    var control_state, input, is_input, is_normal, keypress, normal;
    control_state = 'normal';
    input = function() {
      control_state = 'input';
      return console.log('state', control_state);
    };
    is_input = function() {
      return control_state === 'input';
    };
    normal = function() {
      control_state = 'normal';
      return console.log('state', control_state);
    };
    is_normal = function() {
      return control_state === 'normal';
    };
    keypress = function(evt) {
      switch (evt.which) {
        case 97:
          if (is_normal()) {
            return add_dictionary_note();
          }
      }
    };
    return {
      input: input,
      normal: normal,
      keypress: keypress
    };
  };

  state = init_state();

  add_dictionary_note = function() {
    var cancel_button, dialog, key, save_button;
    key = window.getSelection().toString() || 'hello world';
    console.log(key);
    dialog = $(dictionary_form({
      key: key,
      value: dictionary[key]
    }));
    save_button = $('<button class="btn btn-success">Save</button>').click(function() {
      add_to_dictionary(key, dialog.find('textarea').val(), $('p'));
      dialog.remove();
      return state.normal();
    });
    cancel_button = $('<button id="cancel" class="btn btn-danger">Cancel</button>').click(function() {
      dialog.remove();
      return state.normal();
    });
    dialog.append(save_button, cancel_button);
    state.input();
    return $('body').append(dialog);
  };

  $(function() {
    $('p').bindDictionaryLookup();
    $(document).keypress(state.keypress);
    return $(window).on('unload', function() {
      return save_dictionary();
    });
  });

}).call(this);
