// Generated by CoffeeScript 1.6.1
(function() {
  var AllReady,
    _this = this;

  _.zfill = function(x, padding) {
    var i, zeroes;
    zeroes = ((function() {
      var _i, _results;
      _results = [];
      for (i = _i = 0; 0 <= padding ? _i <= padding : _i >= padding; i = 0 <= padding ? ++_i : --_i) {
        _results.push('0');
      }
      return _results;
    })()).join('');
    return (zeroes + x).slice(-1 * padding);
  };

  window.requestAnimationFrame = window.requestAnimationFrame || window.webkitRequestAnimationFrame || window.mozRequestAnimationFrame || function(callback) {
    return window.setTimeout(callback, 1000 / 60);
  };

  AllReady = (function() {

    function AllReady(onReady) {
      var _this = this;
      this.onReady = onReady;
      this.ready = function(id) {
        return AllReady.prototype.ready.apply(_this, arguments);
      };
      this.id = 0;
      this.checklist = {};
    }

    AllReady.prototype.wait = function() {
      var get_callback;
      this.id += 1;
      this.checklist[this.id] = false;
      get_callback = function(id, ready) {
        var _this = this;
        return function() {
          return ready(id);
        };
      };
      return get_callback(this.id, this.ready);
    };

    AllReady.prototype.ready = function(id) {
      this.checklist[id] = true;
      if (_.reduce(this.checklist, (function(a, b) {
        return a && b;
      }), true)) {
        return this.onReady();
      }
    };

    return AllReady;

  })();

  window.AllReady = AllReady;

}).call(this);
