// Generated by CoffeeScript 1.6.1
(function() {
  var $;

  $ = jQuery;

  $(function() {
    var $pause, $play, ad, animate, bd, cube, dimensions, play, svg;
    dimensions = 5;
    svg = new svglib.SVG('#surface', 300, 300, Math.sqrt(dimensions));
    cube = new hypercube.Hypercube(dimensions);
    cube.reset(svg);
    $('#matrix').html(cube.matrix.html());
    ad = 0;
    bd = 1;
    play = true;
    animate = function() {
      cube.rotate(ad, bd, 5);
      $('#matrix').html(cube.matrix.html());
      if (Math.random() < 0.05) {
        ad = Math.floor(Math.random() * 2);
        bd = Math.floor(Math.random() * (dimensions - 2)) + 2;
      }
      if (play) {
        return setTimeout(animate, 40);
      }
    };
    animate();
    $('#reset').click(function() {
      return cube.reset(svg);
    });
    $play = $('#play_pause .play');
    $pause = $('#play_pause .pause');
    $('#play_pause').click(function() {
      play = !play;
      if (play) {
        setTimeout(animate, 40);
        $play.hide();
        return $pause.show();
      } else {
        $play.show();
        return $pause.hide();
      }
    });
    $('#play_pause .play').hide();
    return $('.widget_block').show();
  });

}).call(this);
