// Generated by CoffeeScript 1.6.1
(function() {

  window.hypercube_tests = function() {
    var Matrix;
    module('Matrix tests');
    Matrix = matrix.Matrix;
    test("Zero filled matrix can be created", function() {
      var m;
      m = new Matrix(2, 2);
      return deepEqual(m.data, [[0, 0], [0, 0]]);
    });
    test("Mutiplication to identity matrix", function() {
      var a, b;
      a = new Matrix(2, 2, [[1, 2], [3, 4]]);
      b = new Matrix(2, 2, [[1, 0], [0, 1]]);
      deepEqual(a.data, a.mult(b).data);
      return deepEqual(a.data, b.mult(a).data);
    });
    test("180 degree rotation of 2d vector", function() {
      var a, b;
      a = new Matrix(2, 1, [[1, 2]]);
      b = new Matrix(2, 2, [[-1, 0], [0, -1]]);
      return deepEqual(a.mult(b).data, [[-1, -2]]);
    });
    return test("Mutliplicating of random matrices", function() {
      var a, b, c;
      a = new Matrix(3, 2, [[1, 2, 3], [4, 5, 6]]);
      b = new Matrix(2, 3, [[1, 2], [3, 4], [5, 6]]);
      c = a.mult(b);
      return deepEqual(c.data, [[22, 28], [49, 64]]);
    });
  };

}).call(this);
