version: '3'

services:
    server:
        image: server
        build:
            context: .
            dockerfile: nginx.docker
        ports:
            - 8080:80
            - 8083:443
    backend:
        image: backend
        build:
            context: .
            dockerfile: backend.docker
