// Generated by CoffeeScript 1.6.1
(function() {
  var $, Tree, parse_tree;

  $ = jQuery;

  Tree = (function() {

    function Tree(container_selector, diameter) {
      this.diameter = diameter != null ? diameter : 900;
      this.tree = d3.layout.tree().size([360, this.diameter / 2 - 120]).separation(function(a, b) {
        return (a.parent === b.parent ? 1 : 2) / a.depth;
      });
      this.diagonal = d3.svg.diagonal.radial().projection(function(d) {
        return [d.y, d.x / 180 * Math.PI];
      });
      this.svg = d3.select(".widget_block").append("svg").attr("width", this.diameter).attr("height", this.diameter - 150).append("g").attr("transform", "translate(" + (this.diameter / 2) + ", " + (this.diameter / 2) + ")");
    }

    Tree.prototype.draw = function(root) {
      var link, links, node, nodes;
      nodes = this.tree.nodes(root);
      links = this.tree.links(nodes);
      link = this.svg.selectAll(".link").data(links).enter().append("path").attr("class", "link").attr("d", this.diagonal);
      node = this.svg.selectAll(".node").data(nodes).enter().append("g").attr("class", "node").attr("transform", function(d) {
        return "rotate( " + (d.x - 90) + ")translate(" + d.y + ")";
      });
      node.append("circle").attr("r", 4.5);
      return node.append("text").attr("dy", ".31em").attr("text-anchor", function(d) {
        if (d.x < 180) {
          return "start";
        } else {
          return "end";
        }
      }).attr("transform", function(d) {
        if (d.x < 180) {
          return "translate(8)";
        } else {
          return "rotate(180)translate(-8)";
        }
      }).text(function(d) {
        return d.name;
      });
    };

    return Tree;

  })();

  parse_tree = function(text) {
    var res;
    res = text.split('\n');
    return console.log(res);
  };

  $(function() {
    var tree;
    $('.widget_block').show();
    tree = new Tree('.widget_block', 900);
    tree.draw({
      "name": "flare",
      "children": [
        {
          "name": "analytics"
        }, {
          "name": "asdasf"
        }, {
          "name": "asdfsd11111;",
          children: [
            {
              "name": "1"
            }, {
              "name": "2"
            }, {
              "name": "3"
            }
          ]
        }, {
          "name": "taras"
        }
      ]
    });
    return $('#submit_button').click(function() {
      return tree.draw(parse_tree($('#edit_code').val()));
    });
  });

}).call(this);
