// Generated by CoffeeScript 1.6.1
(function() {
  var $, diagonal, diameter, draw_tree, svg, tree;

  $ = jQuery;

  $(function() {
    return $('.widget_block').show();
  }, diameter = 900, tree = d3.layout.tree().size([360, diameter / 2 - 120]).separation(function(a, b) {
    return (a.parent === b.parent ? 1 : 2) / a.depth;
  }), diagonal = d3.svg.diagonal.radial().projection(function(d) {
    return [d.y, d.x / 180 * Math.PI];
  }), svg = d3.select(".widget_block").append("svg").attr("width", diameter).attr("height", diameter - 150).append("g").attr("transform", "translate(" + (diameter / 2) + ", " + (diameter / 2) + ")"), draw_tree = function(root) {
    var link, links, node, nodes;
    nodes = tree.nodes(root);
    links = tree.links(nodes);
    link = svg.selectAll(".link").data(links).enter().append("path").attr("class", "link").attr("d", diagonal);
    node = svg.selectAll(".node").data(nodes).enter().append("g").attr("class", "node").attr("transform", function(d) {
      return "rotate( " + (d.x - 90) + ")translate(" + d.y + ")";
    });
    node.append("circle").attr("r", 4.5);
    return node.append("text").attr("dy", ".31em").attr("text-anchor", function(d) {
      if (d.x < 180) {
        return "start";
      } else {
        return "end";
      }
    }).attr("transform", function(d) {
      if (d.x < 180) {
        return "translate(8)";
      } else {
        return "rotate(180)translate(-8)";
      }
    }).text(function(d) {
      return d.name;
    });
  }, d3.select(self.frameElement).style("height", diameter - 150 + "px"), draw_tree({
    "name": "flare",
    "children": [
      {
        "name": "analytics"
      }, {
        "name": "asdasf"
      }, {
        "name": "asdfsd11111;",
        children: [
          {
            "name": "1"
          }, {
            "name": "2"
          }, {
            "name": "3"
          }
        ]
      }, {
        "name": "taras"
      }
    ]
  }));

}).call(this);
