// Generated by CoffeeScript 1.6.1
(function() {
  var $;

  $ = jQuery;

  $(function() {
    var animate, i;
    $('.widget_block').show();
    $('svg line').attr('stroke-dasharray', 30);
    i = 0;
    animate = function() {
      i -= 2;
      if (i > 30) {
        i = 0;
      }
      return $('svg line').attr('stroke-dashoffset', i);
    };
    return setInterval(animate, 100);
  });

}).call(this);
